spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password:
      url: jdbc:mysql://localhost/cms?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
server:
  context-path: /cms

file:
  staticAccessPath: '/upload/**'
  uploadFolder: 'D:\\file'